name: hy_lyap_ce
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - python=3.7.11
  - seaborn=0.11.2
  - pip:
    - matplotlib==3.5.3
    - numpy==1.21.3
    - pip==23.3.2
    - scipy==1.7.1
